### ISSUE TITLE
스프린트 1주차

### ISSUE THREAD

**Issue by doong-jo** [connect-foundation/2019-12#1]
## 스프린트 1주차
1인당 페이지 단위 개발 
### 1일차
- Backlog 정리
- 디렉토리 / lint 등 프로젝트 개발 환경 세팅

### 2일차
- DB 구조 작성 (migration + modeling)
- API 문서 작성 (Swagger.io)
- Infra 확정 (예약 서버에 대한 redis 검증 / FE 배포 인프라 확정)
- TEST 구성
    - BE, FE 에 대한 디렉토리 / branch 별 테스팅에 대한 config 설정해야함
    - DB 테스팅을 위한 Travis - BE 테스트 환경 조성해야함
- front 개발 시작
    - 로그인 / 메인
        - 로그인과 메인의 레이아웃 먼저 구성 후에, 컴포넌트를 이어서 작성.
        - Testing 에 대한 길라잡이.

### 3일차
- 2일차 프로젝트 리뷰
    - 미흡한 부분 추출 / TEST 코드에 대한 공부 및 검증
- 2일차에서 미비했던 Feature 이어서 개발
    - FE 레이아웃 작성 이어서 시작
    - Backend API / DB 작성 완료시, 개발시작과 함께 Test 검증해야함.
- backend 개발 시작
    - Frontend 에 필요한 데이터 우선 (로그인과 메인페이지)
    - Oauth 공부 feature 뽑아내기;

### 4일차: 19시 코드 프리징
- 3일차 프로젝트 리뷰
    - BE, FE 에 대한 초기 코드 검증
- 3일차 Feature 이어서 개발
    - 컴포넌트와 테스팅에 관련된 모든 것들 가져오기
- 배포
    - Server-Master, Client-Master 에 PR 및 배포
    - CD 구성은 아직 안되어있기에 일단 수동 배포

### 5일차: 배포
- 코드리뷰 받을 코드 정리
    - 이야기하기 (그때 뽑힌거 보고 ㄱ)

**Comment by FullOfOrange** [comment]
이슈화 되었으며, 프로젝트 칸반에 올라갔고, 일 분배가 끝났기에 이슈를 닫습니다.
