### ISSUE TITLE
BUG: DB의 id값들이 모두 autoincreasement가 되어야함.

### ISSUE THREAD

**Issue by FullOfOrange** [connect-foundation/2019-12#101]
### 테스트 환경
일반적인 실행환경

### 수행 절차
User 데이터베이스에 데이터를 추가하려고 하다 보니까, id 값이 autoIncreasement가 아니었음.

### 오류 내용
수행 절차와 동일

### 기대 결과
Decorater를 추가하여 이것을 autoincreasement가 될 수 있도록 함.

**Comment by dobest27** [comment]
완료 :+1
