### ISSUE TITLE
컴포넌트들에 대한 엔트리 포인트 작성 

### ISSUE THREAD

**Issue by inthewalter** [connect-foundation/2019-12#103]
### Explanation

```js
import {
  PageTemplate, Header, Hero, Footer, FeatureList,
} from 'components'
```
이런 방식으로 Atom, Molecule, Organism 상관없이 components로 묶어서 import할 수 있다. 

-> Components/index.ts 하나를 만들어서 묶어주는 엔트리 포인트 하나가 있으면 좋을 듯
전체적인 코드 리팩토링이 필요하기 때문에 코드 프리징 이후에 하는 것이 좋겠음
[관련 링크](https://github.com/diegohaz/arc/blob/master/src-example/components/index.js)

**Comment by doong-jo** [comment]
YH style 사용으로 결정
`하위로 가는건 상대 경로로
위로 가는건 바로 src기준으로`
