### ISSUE TITLE
BUG: travis 에서 동일한 사유로 계속해서 테스팅이 실패함

### ISSUE THREAD

**Issue by FullOfOrange** [connect-foundation/2019-12#108]
### 테스트 환경
트레비스
### 수행 절차
travis
### 오류 내용
서버의 시딩 오류, 클라는 테스트 오류가 지속적으로 발생함
### 기대 결과
서버는 제가 할테니 클라는 누가 좀 해주세요
### 참고(스크린샷 등)
없음

**Comment by dobest27** [comment]
done
