### ISSUE TITLE
서버에서 개발환경 PORT 변수화

### ISSUE THREAD

**Issue by dobest27** [connect-foundation/2019-12#112]
### Explanation

서버 개발시 로컬에서 실행하면 default 3000 포트로 돌게 설정되어 있습니다만
리액트 클라언트와 동일한 포트라 환경변수화가 필요할 것 같습니다

**Comment by FullOfOrange** [comment]
좋습니다. 클라쪽 env가 생기면 충분히 괜찮을 것 같아요.

**Comment by dobest27** [comment]
done
