### ISSUE TITLE
Page -> BasedTemplate로 변경 제안

### ISSUE THREAD

**Issue by inthewalter** [connect-foundation/2019-12#116]
### Explanation

- 현재 Page 컴포넌트가 있는데, 그 안에는 template만이 존재
- page로서의 기능은 아니고 template으로서의 기능만 수행
  - header와 footer를 template화

따라서 네이밍을 Page -> BasedTemplate로 변경 제안
관련 PR:

**Comment by doong-jo** [comment]
동의합니다 😀

**Comment by inthewalter** [comment]
> 동의합니다 😀

@doong-jo PR 커밋 중인데 다른 곳에서 버그가 있어 성동님 태그 중이었습니다 ㅎㅎ잠시만요

**Comment by dobest27** [comment]
👍

**Comment by dobest27** [comment]
done
