### ISSUE TITLE
[2/2MD] OAuth 로그인에 필요한 API

### ISSUE THREAD

**Issue by dobest27** [connect-foundation/2019-12#12]

**Comment by FullOfOrange** [comment]
Passport + Google Oauth를 사용할 예정임.

**Comment by FullOfOrange** [comment]
passport에 state라는 옵션이 있음. 모든 oauth에 state 라고 해서 로그인을 할 때 callback으로 넘어오는 인자를 이용할 수 있도록 (예를 들면 메인 페이지에서 상세 페이지로 넘어가는 와중에 로그인을 할 경우, 다시 main으로 넘기는게 아니라 상세페이지로 넘어가도록 상태를 옮겨주는 거) 해주어야함. 하지만 이런 인자가 따로 google-oauth에 없음. 이것을 조금 알아봐야할 듯

**Comment by inthewalter** [comment]
#109 머지완료
