### ISSUE TITLE
DB Model을 수정해야합니다.

### ISSUE THREAD

**Issue by dobest27** [connect-foundation/2019-12#125]
### Explanation

데이터베이스 모델을 수정합니다. 관련된 API도 필요하다면 수정해야합니다.
![bookus2 (1)](https://user-images.githubusercontent.com/6308222/69711602-ae6c4180-1144-11ea-8120-5a27296db7b5.png)

**Comment by dobest27** [comment]
Event 에 위도 경도 필드를 추가해야 합니다.
related with #154

**Comment by FullOfOrange** [comment]
확인했습니다. 이어받아서 작업하겠습니다.

**Comment by FullOfOrange** [comment]
google_o_auth_token 을 googleId 라는 필드명으로 변경해서 사용하겠습니다.

**Comment by FullOfOrange** [comment]
deviceToken이 과연 필요할까요?

**Comment by dobest27** [comment]
done
