### ISSUE TITLE
getEvents Service가 기대대로 동작하지 않음

### ISSUE THREAD

**Issue by inthewalter** [connect-foundation/2019-12#134]
### 테스트 환경
로컬 환경

### 수행 절차
infinite scroll을 할 때

`/api/events`를 수행하고 마지막 이벤트의 id를 담아서 
`/api/events?lastId=N`라고 수행

를 반복

### 오류 내용
- lastId부터 그 다음 이벤트들이 넘어오는 게 아니라 계속해서 같은 이벤트들이 결과로 나옴
```js
export async function getEvents(limit = 20, lastId: number): Promise<Event[]> {
  const where: WhereOptions = lastId
    ? { isPublic: true, id: { [Op.gt]: lastId } }
    : { isPublic: true };
```
내림차순으로 정렬을 하고 있기 때문에 `[Op.gt]: lastId` 가 아닌 `[Op.lt]: lastId`로 설정되어야 할 것 같음

**추가적으로** 현재는 `lastId`기준으로 쿼리를 날려서 `startAt`을 기준으로 내림차순 정렬을 하는데 이렇게 될 경우 쿼리가 쌓일 수록 역전현상이 발생해 중복된 데이터가 넘어옴 따라서 lastId가 아닌 startAt을 기준으로 쿼리를 날려야 할 것 같기도 하고,,, 자세한 건 개인적으로 말씀드리겠습니다.

### 기대 결과
정상적으로 중복되지 않고, 순차적으로 데이터가 넘어와야함

### 참고(스크린샷 등)
없음

**Comment by dobest27** [comment]
done
