### ISSUE TITLE
Event Master -> Detail 이동시 스크롤이 유지되는 문제

### ISSUE THREAD

**Issue by dobest27** [connect-foundation/2019-12#146]
### 테스트 환경
foorg.xyz

### 수행 절차
메인에서 스크롤을 내린 후 아이템 선택

### 오류 내용
메인 페이지의 스크롤이 그대로 디테일 페이지에도 이어짐

### 기대 결과
디테일 페이지의 최상단으로 이동

### 참고(스크린샷 등)
![aa](https://user-images.githubusercontent.com/6308222/69842768-da540800-12a7-11ea-9d1c-b99fdd423a75.gif)

**Comment by FullOfOrange** [comment]
#159 와 같이 해결해야 하는 문제임
