### ISSUE TITLE
[0.5MD] 이벤트 정보를 Global 상태로 저장 (Store)

### ISSUE THREAD

**Issue by doong-jo** [connect-foundation/2019-12#148]
### Explanation

이벤트 정보를 Global 상태로 저장하고 이벤트 상세에서 이를 재사용하도록 구현

계성 State가 끝나는 순간 바로 이어 받아서 진행할 예정

**Comment by inthewalter** [comment]
다른 피쳐해결하고 붙잡겠습니다.

**Comment by inthewalter** [comment]
#213 머지완료
