### ISSUE TITLE
[1/0.5MD] 계정을 Global 상태로 저장 (Store)

### ISSUE THREAD

**Issue by doong-jo** [connect-foundation/2019-12#149]
### Explanation

계정 정보를 Global 상태로 저장하고 이를 다른 페이지에서 재사용하도록 구현

**Comment by FullOfOrange** [comment]
Global Store를 지정하고, 그것을 Header와 연동해서 로그인 상태를 표기함.

**Comment by FullOfOrange** [comment]
#173 으로 진행중

**Comment by FullOfOrange** [comment]
#173 머지되어 클로즈함
