### ISSUE TITLE
Travis에서 Develop 브랜치를 Merge 할 때 테스트용 Image를 만들어 줘야함.

### ISSUE THREAD

**Issue by FullOfOrange** [connect-foundation/2019-12#156]
### Explanation

Master Release 를 하기 이전에 수동으로 통합 테스트를 하기 위한 테스트 이미지를 Develop 브랜치가 머지될 때마다 할 수 있도록 만들어야함.

따로 버전 태깅을 하진 않을 예정임.

**Comment by inthewalter** [comment]
일전에 완료함
