### ISSUE TITLE
이벤트 위치(위도, 경도) 데이터 스크립트 추가

### ISSUE THREAD

**Issue by doong-jo** [connect-foundation/2019-12#162]
### Explanation

이벤트 장소의 위도 경도 주소가 필요합니다.
GoogleAPI 를 이용해서 주소 변환을 하고 lat, lng를 넣어야합니다.

**Comment by inthewalter** [comment]
데이터 수정완료
https://fullofstack.slack.com/archives/CPW2PSH1P/p1575267485000100
