### ISSUE TITLE
[2/2MD] 티켓 구매용 단독 서버를 만들어야함.

### ISSUE THREAD

**Issue by FullOfOrange** [connect-foundation/2019-12#166]
### Explanation

티켓 구매용 API 서버가 혼자서 트래픽을 견딜 수 있도록 단독 서버가 필요함.

**Comment by FullOfOrange** [comment]
일단은 유저 라우팅을 이용해서 단독 서버를 따로 두지 않고 개발할 예정임.

**Comment by doong-jo** [comment]
merge and close
