### ISSUE TITLE
[2MD] 이벤트 만들기 API 'POST /events'

### ISSUE THREAD

**Issue by FullOfOrange** [connect-foundation/2019-12#168]
### Explanation

이벤트를 만들때 필요한 API를 생성해야함.

- [ ] createEvent
- [ ] createTicket
    - [ ] Transaction
- [ ] uploadImg (required)

**Comment by FullOfOrange** [comment]
${ticket_type_id}: {
    id,
    isBlock,
    salesStartAt,
    salesEndAt,
}
이런식으로 추가해야할 겁니다.  DB에서 나온 값 그대로 추가했으니까 똑같이 하시면 될 것 같아요

**Comment by dobest27** [comment]
done
