### ISSUE TITLE
Travis Master에서 발생하는 build error를 해결해야함.

### ISSUE THREAD

**Issue by FullOfOrange** [connect-foundation/2019-12#171]
### 테스트 환경
Travis 

### 수행 절차
Travis Client master deploy 과정에서 일어남

### 오류 내용
사용하지 않는 Variable이 에러 코드를 내면서 return 됨. 

### 기대 결과
build | fail 을 success 로 변경이 가능함.

**Comment by inthewalter** [comment]
예-해!
