### ISSUE TITLE
Btn에서 발생하는 warning 제거

### ISSUE THREAD

**Issue by doong-jo** [connect-foundation/2019-12#176]
### 테스트 환경
브라우저 상 warning

### 수행 절차
grow, fit prop 수정

### 오류 내용
grow, fit props에 대한 non-boolean warning

### 기대 결과
warning 제거

### 참고(스크린샷 등)
<img width="746" alt="스크린샷 2019-12-02 오후 7 50 59" src="https://user-images.githubusercontent.com/22005861/69953691-19e75200-153d-11ea-9c69-de5d890d4b7b.png">

**Comment by inthewalter** [comment]
#179 에서 다룰 예정이므로 이슈 닫도록 하겠습니다.
