### ISSUE TITLE
LoginBtn (로그인 버튼)

### ISSUE THREAD

**Issue by doong-jo** [connect-foundation/2019-12#18]
<img width="551" alt="스크린샷 2019-11-11 오후 1 44 47" src="https://user-images.githubusercontent.com/22005861/68561577-6fbe6200-0489-11ea-9e5c-360a29fef4ab.png">

# LoginBtn (로그인 버튼)
### 페이지
로그인 페이지 #17 

### 설명
- 클릭 시, OAuth과정을 거친 후 해당 유저의 데이터가 데이터베이스에
    - 있으면 메인 페이지로 이동 (로그인)
    - 없으면 회원가입 페이지로 이동 (회원가입)

**Comment by inthewalter** [comment]
새로운 feature로 재작성할 예정
