### ISSUE TITLE
Axios 를 모아두는 곳을 만들어야함.

### ISSUE THREAD

**Issue by FullOfOrange** [connect-foundation/2019-12#183]
### Explanation

생각보다 useFetch를 자유롭게 쓰는것이 제한되고, Axios의 활용이 더 많이 필요해지면서 Axios 관련 메소드를 모아두고 모든 호출들을 이것으로 Refactoring 해주어야함.

**Comment by doong-jo** [comment]
#196 과 중복되어 close
