### ISSUE TITLE
Client Type이 겹칩니다.

### ISSUE THREAD

**Issue by FullOfOrange** [connect-foundation/2019-12#187]
### Explanation

Data.ts와 Event.ts를 보시면 이벤트 디테일과 메인페이지에서 사용하는 interface가 겹칩니다. 이것을 수정해야할 것 같아요.

**Comment by doong-jo** [comment]
@inthewalter  님과 같이 수정하겠습니다

**Comment by doong-jo** [comment]
mege and close
