### ISSUE TITLE
스토리북 실행 시 SignUp Knob이 바로 표시됨

### ISSUE THREAD

**Issue by dobest27** [connect-foundation/2019-12#194]
### 테스트 환경
로컬

### 수행 절차
구글맵 위치에서 새로고침

### 오류 내용
상관없는 페이지에서 회원가입의 knobs가 나타남

### 기대 결과
해당 컴포넌트의 knobs 만 표시

### 참고(스크린샷 등)
![image](https://user-images.githubusercontent.com/6308222/70118250-df9bc300-16aa-11ea-9acc-418506094bd7.png)

**Comment by inthewalter** [comment]
`index.stories.tsx` 내용 좀 공유해주실 수 있나요?
제 브런치에는 아예 addon관련 코드가 없어서

**Comment by inthewalter** [comment]
#229
