### ISSUE TITLE
[BUG] 상세 페이지 가격과 예매 가격이 다름

### ISSUE THREAD

**Issue by jonghwajoa** [connect-foundation/2019-12#230]
### Explanation

상세 페이지는 16만원인데

![image](https://user-images.githubusercontent.com/31912670/70298293-7e9ff680-1834-11ea-81da-732d385ec7bb.png)

![image](https://user-images.githubusercontent.com/31912670/70298309-8cee1280-1834-11ea-98e6-62f9a28864e2.png)
예매 페이지에서는 만원

**Comment by doong-jo** [comment]
아직 미구현 상태라 그렇습니다. 알려주셔서 감사해요!

**Comment by doong-jo** [comment]
solve and close
