### ISSUE TITLE
회원가입 시 잘못된 값 입력해도 회원가입 완료됨

### ISSUE THREAD

**Issue by BuildTheTruth** [connect-foundation/2019-12#232]
### 테스트 환경
크롬
### 수행 절차
회원가입을 누르고 성, 이름에 영어를 입력하고 휴대번호에 아무 값도 입력하지 않고 회원가입 버튼 누름

### 오류 내용
회원가입 때 성, 이름을 영어로 입력하였고 휴대전화 번호는 입력하지 않았는데 경고문은 떴지만, 회원가입이 완료됨

### 기대 결과
회원가입이 안될 줄 알았는데 완료됨

**Comment by doong-jo** [comment]
놓칠뻔했네요. 꼼꼼히 봐주셔서 감사합니다. @FullOfOrange  님 고쳐주세요

**Comment by FullOfOrange** [comment]
#237 과 동일 이슈로 클로즈
