### ISSUE TITLE
티켓구매

### ISSUE THREAD

**Issue by soob-forest** [connect-foundation/2019-12#233]
### 테스트 환경
크롤
### 수행 절차
http://www.foorg.xyz/events/331/register/tickets 접속
티켓구매
### 오류 내용
티켓구매에 실패했습니다.
### 기대 결과
티켓구매
### 참고(스크린샷 등)
![image](https://user-images.githubusercontent.com/34637627/70299938-9b8af880-1839-11ea-8fa0-d30160e70e96.png)

**Comment by FullOfOrange** [comment]
서버 시간은 표준시 00 으로 설정되어있어, 실제로 한국 시간에 맞추기 위해서는 한국 시간 - 9 시간을 한 시간으로 해야함. 그래야 그 시간에 열림. 그것으로 일어난 버그임으로 Close함.
