### ISSUE TITLE
[Bug] 이벤트 상세보기시 스크롤이 맨위가 아님

### ISSUE THREAD

**Issue by jonghwajoa** [connect-foundation/2019-12#234]
메인페이지에서 이벤트 페이지를 클릭하여 상세보기로 이동했을때,
스크롤이 맨위가 아닌, 중간에 위치함.
존재하는 위치도 랜덤인것 같음

![image](https://user-images.githubusercontent.com/31912670/70300554-2f10f900-183b-11ea-8bcb-5466e9fcf56f.png)

**Comment by dobest27** [comment]
감사합니다!
#146 이슈 중복으로 닫습니다
