### ISSUE TITLE
[BUG] 이벤트 페이지 이동 시 스크롤 원 위치 안됨

### ISSUE THREAD

**Issue by dlatns0201** [connect-foundation/2019-12#235]
스크롤을 어느정도 내리고 이벤트 상세 페이지를 들어가면 스크롤이 맨 위쪽으로 이동하지 않아 보기 힘든 현상이 발생

**Comment by dobest27** [comment]
감사합니다~!
이슈 중복으로 닫습니다.
duplicated #146
