### ISSUE TITLE
[Bug] 이벤트 상세 페이지 지도 관련 (Pin 버그)

### ISSUE THREAD

**Issue by jngsoo** [connect-foundation/2019-12#236]
### 테스트 환경
- Chrome 브라우저
- OS X 

### 수행 절차
- 이벤트 상세 페이지에서 아래 부분에 위치한 지도를 조작(위치 조정)

### 오류 내용
- 핀이 지도 가운데 고정돼있습니다!

### 기대 결과
- 핀이 이벤트 장소에 고정돼있으면 좋을 것 같아요.

### 참고(스크린샷 등)
<img width="1244" alt="Screen Shot 2019-12-06 at 3 21 44 PM" src="https://user-images.githubusercontent.com/33929835/70301040-98453c00-183c-11ea-9fb7-69f203e15937.png">

**Comment by doong-jo** [comment]
찾아주셔서 감사합니다.

**Comment by doong-jo** [comment]
merge and close
