### ISSUE TITLE
Live 스토리북에 키가 없어서 구글 지도가 안됨

### ISSUE THREAD

**Issue by dobest27** [connect-foundation/2019-12#241]
### 테스트 환경
https://compassionate-swartz-fe4719.netlify.com

### 수행 절차
GoogleMap Component 클릭

### 오류 내용
구글맵이 표시되지 않음

### 기대 결과
표시되어야함

### 참고(스크린샷 등)
![image](https://user-images.githubusercontent.com/6308222/70329054-d6168480-187d-11ea-8afd-1a5f067f3cbc.png)

**Comment by doong-jo** [comment]
제가 수정해볼게요!

**Comment by doong-jo** [comment]
merge and close
