### ISSUE TITLE
인증(로그인) 여부를 확인하는 미들웨어가 필요함

### ISSUE THREAD

**Issue by dobest27** [connect-foundation/2019-12#251]
### Explanation

인증(로그인) 여부를 확인하고, 확인되지 않으면 401를 반환하는 등의 역할을 하는
requireLoggedIn 미들웨어가 필요함

**Comment by FullOfOrange** [comment]
reserve server에 그 역할을 하는 middleware가 있습니다.. Validation 이 아직 명확하진 않은데 그것을 사용하면 좋을 것 같습니다.
메인 서버에서는 auth api 쪽에 authToken 이라는 미들웨어를 사용하면 인증 로직이 가능할 것 같은데 이부분 제가 정형화 해보겠습니다.

**Comment by FullOfOrange** [comment]
페이지 전환시에 사용할 것이라면 Client로직을 사용하면 좋을 것 같습니다. Global Store에 관련 기능이 있는데 그것도 정형화해서 알려드리겠습니다.

**Comment by dobest27** [comment]
done
