### ISSUE TITLE
Client useStateReducer 디렉터리 이름 잘못됨

### ISSUE THREAD

**Issue by doong-jo** [connect-foundation/2019-12#259]
### 오류 내용
디렉터리 이름 `useStateReduter` -> `useStateReducer`

### 참고(스크린샷 등)
![스크린샷 2019-12-09 오전 1 40 20](https://user-images.githubusercontent.com/22005861/70392587-ddc45d80-1a24-11ea-927e-f2ecae845277.png)

**Comment by dobest27** [comment]
완료~!
