### ISSUE TITLE
EventInfoContainer (마이페이지 - 내티켓 - 이벤트 정보 설명 컨테이너)

### ISSUE THREAD

**Issue by FullOfOrange** [connect-foundation/2019-12#282]
### Component

EventInfoContainer

### Screenshot

<img width="420" alt="스크린샷 2019-12-10 오전 11 05 25" src="https://user-images.githubusercontent.com/10372359/70488728-fb84e600-1b3c-11ea-98f7-718037a87d72.png">

### Page

#272

### Explanation

선택한 이벤트에 대한 상세한 정보를 보여주기 위한 이벤트 정보 컨테이너

**Comment by doong-jo** [comment]
merge and close
