### ISSUE TITLE
TicketCardList (마이페이지 - 내 티켓 - 구매 완료 티켓)

### ISSUE THREAD

**Issue by FullOfOrange** [connect-foundation/2019-12#284]
### Component

TicketCardList

### Screenshot

<img width="300" alt="스크린샷 2019-12-10 오전 11 05 25" src="https://user-images.githubusercontent.com/10372359/70488898-70f0b680-1b3d-11ea-8233-8590caa5563e.jpeg">

### Page

#272

### Explanation

구매한 티켓들을 리스트화 하여 구현함, 각각은 환불버튼과 현재 출석 체크한 여부가 뜨며, 티켓 아이디와 티켓 정보를 보여줌

**Comment by doong-jo** [comment]
merge and close
