### ISSUE TITLE
html lang 설정안됨

### ISSUE THREAD

**Issue by dobest27** [connect-foundation/2019-12#286]
### 테스트 환경
로칼 크롬 최신

### 수행 절차
페이지 접속

### 오류 내용
lang 설정이 안되어서 크롭에서 번역 dialog 가 뜹니다

### 기대 결과
한국어로 설정

### 참고(스크린샷 등)
<img width="256" alt="스크린샷 2019-12-10 오후 12 21 57" src="https://user-images.githubusercontent.com/6308222/70492649-769fc980-1b48-11ea-8403-8d204ca14272.png">

**Comment by FullOfOrange** [comment]
변경 완료, 머지함
