### ISSUE TITLE
API 문서 작성 (Swagger.io)

### ISSUE THREAD

**Issue by inthewalter** [connect-foundation/2019-12#3]

**Comment by inthewalter** [comment]
리뷰 부탁드립니다...
https://app.swaggerhub.com/apis-docs/inthewalter/bookus-api-docs/1.0.0

**Comment by inthewalter** [comment]
request 부분 대폭 수정하고 있읍니다...

**Comment by inthewalter** [comment]
@dobest27 @doong-jo @FullOfOrange 
설명(?)을 제외하고 Request랑 Response 내용에 대해서 피드백부탁드려욤
https://app.swaggerhub.com/apis-docs/inthewalter/bookus-api-docs/0.0.1

**Comment by FullOfOrange** [comment]
시간이 없어서 힘들어짐.
