### ISSUE TITLE
서버 Log를 어떤 방식으로 남길지 결정해야 함.

### ISSUE THREAD

**Issue by FullOfOrange** [connect-foundation/2019-12#30]
서버에 대한 메소드 호출 로그, 접근 로그 등을 어떤식으로 남길지 결정해야 합니다.

**Comment by FullOfOrange** [comment]
오케스트레이션 툴 내에서 로깅을 하는 방법이 있다고 합니다... 이걸 좀 찾아봐야겠네요

**Comment by doong-jo** [comment]
merge and close
