### ISSUE TITLE
req.user.id 런타임 타입이 number 가 아님

### ISSUE THREAD

**Issue by dobest27** [connect-foundation/2019-12#303]
### 테스트 환경
육진혁 테스터님

### 수행 절차
isLogin 미들웨어에서 req.user.id 런타임 타입이 number 가 아니라서 오류남
isLogin 미들웨어 이름을 requiredLogin

**Comment by FullOfOrange** [comment]
미들웨어 이름 바꾸면서 수정하겠습니다. 뭐로 바꿀까요?

**Comment by FullOfOrange** [comment]
해결함
