### ISSUE TITLE
개발 환경 세팅 문서화

### ISSUE THREAD

**Issue by FullOfOrange** [connect-foundation/2019-12#31]

**Comment by doong-jo** [comment]
Docker 관련된 제목으로 수정부탁드려요~

**Comment by FullOfOrange** [comment]
이름 Docker를 이용한 서버 환경 세팅으로 변경하고 Backend라는 이름도 삭제했습니다.
https://github.com/connect-foundation/2019-12/wiki/Docker을-이용한-서버-개발-환경-설정
