### ISSUE TITLE
[BUG] 로그인 후 홈 페이지에서 오른쪽 상단 이름을 클릭하면 404 메시지

### ISSUE THREAD

**Issue by ljh1324** [connect-foundation/2019-12#339]
### 테스트 환경
크롬

### 수행 절차
1. 로그인 후 오른쪽 상단 이름 클릭

### 오류 내용
1. 요청에 실패했습니다 404 에러가 보임

### 참고(스크린샷 등)
![](https://i.imgur.com/ZaTPfaB.png)

**Comment by sjh2428** [comment]
로그아웃을 하고나서도 한번 뜹니다!

**Comment by sjh2428** [comment]
처음에 로그아웃 하면 로그인 화면으로 가지더니 두번째로 로그아웃 하면 여기에 멈춰있네요
![image](https://user-images.githubusercontent.com/26241585/70772178-13679e80-1db7-11ea-9588-a9a8c1105db4.png)

**Comment by FullOfOrange** [comment]
#352 로써 해결되는 이슈임
