### ISSUE TITLE
[BUG] 로그아웃시 404 에러 메시지가 보여짐

### ISSUE THREAD

**Issue by ljh1324** [connect-foundation/2019-12#340]
### 테스트 환경
크롬

### 수행 절차
1. 로그인 후 오른쪽 상단의 프로필 화면으로 들어감
2. 프로필 화면에서 로그아웃 클릭

### 오류 내용
1. 404 에러 메시지가 보임

### 참고(스크린샷 등)
![](https://i.imgur.com/5BTeXH8.png)

**Comment by FullOfOrange** [comment]
#352 와 같이 해결해야 하는 이슈로 클로즈
