### ISSUE TITLE
[BUG] 두번째 로그아웃시 로그인 화면으로 안가집니다

### ISSUE THREAD

**Issue by sjh2428** [connect-foundation/2019-12#341]
### 테스트 환경
Chrome
Mac OS

### 수행 절차
로그아웃 한번 하고 재로그인 후 로그아웃을 진행하였습니다

### 오류 내용
첫 로그아웃에서는 로그인 화면으로 넘어갔던 것 같았는데 두번째시도에서는 가지지 않네요

### 기대 결과
동일하게 로그인 화면으로 가야할 것 같습니다

### 참고(스크린샷 등)
![image](https://user-images.githubusercontent.com/26241585/70772394-bf10ee80-1db7-11ea-97dd-ad19e5db8f49.png)

**Comment by FullOfOrange** [comment]
#352 와 같이 해결해야 하는 이슈로 클로즈함
