### ISSUE TITLE
[BUG] 티켓 구매 후 프로필 화면에서 구매한 티켓이 보이지 않음

### ISSUE THREAD

**Issue by ljh1324** [connect-foundation/2019-12#342]
### 테스트 환경
크롬

### 수행 절차
1. 로그인 후 홈 페이지 이벤트 목록 중 하나를 클릭
2. 이벤트 티켓 구입
3. 오른쪽 상단 이름 클릭
4. "내 티켓" 클릭

### 오류 내용
이벤트 티켓을 구입했는데 티켓이 보이지 않음.

**Comment by doong-jo** [comment]
resolve and close
