### ISSUE TITLE
[BUG] http://www.bookus.kr/my/tickets에서 로그인하지 않은 상태로 새로고침시 undefined/404 Alert

### ISSUE THREAD

**Issue by sjh2428** [connect-foundation/2019-12#343]
### 테스트 환경
Mac OS
Chrome

### 수행 절차
로그인하지 않은 상태로 특정 URL 접속

### 오류 내용
404/undefined 알람

### 기대 결과
404/undefined보다는 로그인 페이지나 메인 페이지로 가는 것이 좋을 것 같습니다

### 참고(스크린샷 등)
![image](https://user-images.githubusercontent.com/26241585/70772504-12833c80-1db8-11ea-8b81-2d4fb1cae58f.png)

**Comment by FullOfOrange** [comment]
Private 라우터를 달아서 해결함.
