### ISSUE TITLE
[의견] 수량선택시, 갯수에따른  < > disable

### ISSUE THREAD

**Issue by jonghwajoa** [connect-foundation/2019-12#344]
![수량](https://user-images.githubusercontent.com/31912670/70772550-38a8dc80-1db8-11ea-8ce9-f6bf78087ef4.png)

수량의 범위가 [1,5] 로 보이는데요
1일때는 < 의 버튼이, 5일경우는 > 버튼이 안보여도 될것같습니다.

색상도 이쁘게 바꿔주면 좋을것 같아요

**Comment by doong-jo** [comment]
resolve and close
