### ISSUE TITLE
[BUG] 유효성검사 성과 이름의 문구가 다르게 보여집니다

### ISSUE THREAD

**Issue by WooYeonSeo** [connect-foundation/2019-12#345]
### 테스트 환경
mac chrome 
### 수행 절차
회원가입
### 오류 내용
성과 이름의 유효성 오류가 바뀌어서 보여집니다.
### 기대 결과
두개 바꿔주세요.
영어이름은 안되나요??
### 참고(스크린샷 등)
![image](https://user-images.githubusercontent.com/10355800/70772635-7ad21e00-1db8-11ea-99ab-4528716d4dab.png)

**Comment by doong-jo** [comment]
네 현재는 영어로만 입력이 가능합니다. 감사합니다.

**Comment by doong-jo** [comment]
버그 수정으로 인한 Close
