### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by zoomspeed** [connect-foundation/2019-12#346]
### 테스트 환경
Firefox
### 수행 절차
주최하기 버튼을 눌렀습니다.
### 오류 내용
에러메시지가 뜹니다.
### 참고(스크린샷 등)
![image](https://user-images.githubusercontent.com/12872904/70772664-9806ec80-1db8-11ea-9824-abe07768ec04.png)

![image](https://user-images.githubusercontent.com/12872904/70772624-7279e300-1db8-11ea-9230-0ff3a0573b64.png)

**Comment by inthewalter** [comment]
감사합니다. 다른 브런치에서 작업중인 이슈와 중복되어 닫겠습니다!
