### ISSUE TITLE
[의견] 티켓구매시 비로그인시, 로그인하고 다시 티켓구매창으로 왔으면 좋겠습니다.

### ISSUE THREAD

**Issue by jonghwajoa** [connect-foundation/2019-12#348]
비로그인 상태로 티켓구매요청 -> 로그인페이지 이동 -> 로그인후 이전 페이지로 이동했으면 좋겠습니다.

현재는 index page로 이동합니다.

**Comment by inthewalter** [comment]
로그인이 필요한 페이지에서 로그인을 요청할 떄, 리다이렉트 URL을 담아서 다시 오는 걸로 설계를 했었는데 무언가 정상작동을 하지 않나보네요! 버그로 라벨달겠습니당

**Comment by doong-jo** [comment]
@FullOfOrange 오렌지님 이거 어케..?

**Comment by doong-jo** [comment]
merge and close
