### ISSUE TITLE
[BUG] 티켓 구매 후 재구매 시도

### ISSUE THREAD

**Issue by sjh2428** [connect-foundation/2019-12#349]
### 테스트 환경
맥/크롬

### 수행 절차
동일한 티켓 재구매 3번째 시도

### 오류 내용
가능한 티켓 갯수가 아니라고 뜹니다

### 기대 결과
두번째 재구매 시도시에는 이미 구매한 것이라고 띄워주셨었는데 다시 세번째 시도시 아무런 알람이 뜨지 않더니 아래와 같은 화면이 등장하였습니다

### 참고(스크린샷 등)
![image](https://user-images.githubusercontent.com/26241585/70772784-f9c75680-1db8-11ea-9665-93983c16efe2.png)

**Comment by inthewalter** [comment]
뭔가 잘못되었네요ㅎㅎ 감사합니다!

**Comment by doong-jo** [comment]
resolve and close
