### ISSUE TITLE
HeaderContainer (공통 헤더)

### ISSUE THREAD

**Issue by doong-jo** [connect-foundation/2019-12#35]
### Component
HeaderContainer (공통 헤더)

### Screenshot
<img width="924" alt="스크린샷 2019-11-14 오후 3 24 03" src="https://user-images.githubusercontent.com/22005861/68831851-cbd7ef00-06f2-11ea-9ebb-6dbcb8e397f4.png">

### Page
공통 헤더

### Explanation
- 공통으로 사용되는 컴포넌트를 작성
- 로그인 상태에 따른 분기는 되지 않고 레이아웃만 존재

**Comment by FullOfOrange** [comment]
Base Component에 포함되는 사항이라 이슈를 닫음
