### ISSUE TITLE
[의견] 페이징 기능 추가

### ISSUE THREAD

**Issue by jonghwajoa** [connect-foundation/2019-12#350]
무한스크롤의 단점은 원래 보던지점으로 다시가기위해선, 처음부터 다시 내려가야하는데요.
이를 위해서 일부사이트는 페이징기능과 무한스크롤을 둘다 사용하는것으로 알고있습니다.

페이징 기능 or 무한스크롤을 선택적으로 사용할 수 있으면 좋겠네요

**Comment by FullOfOrange** [comment]
아쉽지만 페이징을 선택할 수 있게 하는 것은 힘들 것 같습니다. 의견은 감사하지만, 지금 적용하기엔 너무 힘이 들 것 같아요.
