### ISSUE TITLE
[BUG] 로그아웃 버그

### ISSUE THREAD

**Issue by jonghwajoa** [connect-foundation/2019-12#351]
![image](https://user-images.githubusercontent.com/31912670/70773032-a0abf280-1db9-11ea-99b8-d7afa3ce70e8.png)

로그아웃시 로그아웃이 성공했습니다 alert이후
위와 같은 alert가 추가적으로 발생하네요

**Comment by inthewalter** [comment]
로그인에 따른 라우팅처리를 개발 중이에요 ㅠ 감사합니다다

**Comment by FullOfOrange** [comment]
#352 같이 처리해야 할 로직이므로 이 이슈는 닫도록 함.
