### ISSUE TITLE
[BUG] 로그아웃 이후에도 내 티켓이 보임

### ISSUE THREAD

**Issue by jonghwajoa** [connect-foundation/2019-12#352]
![image](https://user-images.githubusercontent.com/31912670/70773095-d5b84500-1db9-11ea-8fb5-b5d607d49b62.png)

로그그아웃 후에도 내티켓이 보입니다.

**Comment by inthewalter** [comment]
로그그아웃하고 상태를 초기화해줬어야할 거 놓쳤네요 감사합니다다

**Comment by FullOfOrange** [comment]
로그아웃 상태 초기화 완료 및 Private Router 도입으로 인한 이슈 클로즈
