### ISSUE TITLE
[BUG] 로그인 상태에서 /login url이동시 로그인 페이지로 이동

### ISSUE THREAD

**Issue by jonghwajoa** [connect-foundation/2019-12#353]
로그인상태에서 url로 /login 이동시 다시 로그인 할수 있네요.
의도한 사항인지 몰라서 일단 올려봅니다.

**Comment by FullOfOrange** [comment]
알려주셔서 감사합니다.
말씀하신 사항이 의도되지 않은 접근이긴 하지만, 로직상 로그인을 재시도 해도 (설령 회원가입이 필요한 회원이거나 다른 회원이라도) 서비스 이용에 문제가 없을 것이라고 생각합니다. 알려주셔서 감사합니다.
