### ISSUE TITLE
[BUG] 회원가입 시 오류 메시지 잘못나옴

### ISSUE THREAD

**Issue by young-do** [connect-foundation/2019-12#355]
### 수행 절차
google oauth 로그인 후 회원가입 폼 입력 

### 오류 내용
성, 이름 오류 메시지가 번갈아서 나와요.. ㅋㄷㅋㄷ

### 참고(스크린샷 등)
![](https://i.imgur.com/hN7n4xE.png)

**Comment by inthewalter** [comment]
오 감사합니다!

**Comment by doong-jo** [comment]
버그 수정으로 인한 Close
