### ISSUE TITLE
[의견] 지도맵 마우스로 이동

### ISSUE THREAD

**Issue by jonghwajoa** [connect-foundation/2019-12#357]
![image](https://user-images.githubusercontent.com/31912670/70776132-8d9c2100-1dbf-11ea-9773-b29b53a1df4e.png)

마우스 드래그로 이동하고 싶은데 안되네요.
\+ \- 버튼만으로는 주변을 살펴보기에 제한적인것 같습니다.

**Comment by inthewalter** [comment]
개선중이에요 감사합니다!

**Comment by inthewalter** [comment]
#330 merge completed
