### ISSUE TITLE
[BUG] 페이지별 date format이 다름

### ISSUE THREAD

**Issue by jonghwajoa** [connect-foundation/2019-12#358]
![image](https://user-images.githubusercontent.com/31912670/70776199-bf14ec80-1dbf-11ea-8d3b-1055ca35aaca.png)

![image](https://user-images.githubusercontent.com/31912670/70776223-d18f2600-1dbf-11ea-9745-f482daac4afc.png)

아직 작업이 완료되지 않아서 그런것 같은데요.!
혹시나 해서 올려봅니다.

**Comment by inthewalter** [comment]
미처 넣지 못했었는데 감사해요~

**Comment by doong-jo** [comment]
해결로 인한 close
