### ISSUE TITLE
[BUG] 종료일자 계산 오류

### ISSUE THREAD

**Issue by jonghwajoa** [connect-foundation/2019-12#359]
![image](https://user-images.githubusercontent.com/31912670/70776454-73167780-1dc0-11ea-8669-ca7281df3ac5.png)

작년에 마감된 이벤트인데
66478일 후에 판매마감 되네요

**Comment by inthewalter** [comment]
182년뒤에 마감이네요 감사합니다ㅋㅋ

**Comment by doong-jo** [comment]
실제로 DB에 2200년으로 저장되어있었네요..🤦‍♂️ 이슈에 등록해주셔서 감사합니다! @jonghwajoa 

해결로 인한 close
