### ISSUE TITLE
[토론] 로그에는 어떤 정보를 담아야 할까요?

### ISSUE THREAD

**Issue by FullOfOrange** [connect-foundation/2019-12#363]
### Explanation

제목과 마찬가지입니다. 어떤 정보를 로깅을 해야 할까요? Error 같은 경우에는 에러의 형태를 로깅하면 될 수 있는데 req, res 를 어떤식으로 보냈었는지 남겨야할 것 같습니다. 이것을 어떻게 남겨야 할까요?

**Comment by doong-jo** [comment]
생각나는대로 적어본다면
`method`, `url`, `status`, `milliseconds`, `request`, `response`

ex.
`GET /api/**/* 500 2.386 ms 
{...request}
{...response}`

이런 형식 어떨까요?

**Comment by FullOfOrange** [comment]
해결됨
