### ISSUE TITLE
Webpack alias 설정하기

### ISSUE THREAD

**Issue by dobest27** [connect-foundation/2019-12#37]
### Explanation

지금 Frontend 디렉토리 구조 상 뎁스가 매우 깊습니다.
앞으로도 계속해서 깊어질 것 같은데,
이를 Webpack의 alias 같은 설정을 찾아서 설정하면
코드의 깔끔함과 편리함을 찾을 수 있을 것 같습니다!

**Comment by doong-jo** [comment]
#246 과 중복되므로 close
