### ISSUE TITLE
axios status code 200 이 아닐때 콘솔에 안뜨게 하기

### ISSUE THREAD

**Issue by dobest27** [connect-foundation/2019-12#394]
### Explanation
- axios status code 200 이 아닐때 콘솔에 에러 안뜨게 하기
- axios.create(validateStatus) 를 통해 가능합니다
- https://github.com/axios/axios#handling-errors

### 참고사항
- 에러가 안뜨게 되는 것이라서 axios.get().then().catch() 에서 기존 catch 에 들어오는 로직이 then 으로 들어오게 됩니다

**Comment by FullOfOrange** [comment]
이것을 변경할 경우 useApiRequest로직이 많이 변경될 것임. 또한 Console.log로 뜨는것이 사용자입장에서 별로 상관이 없을 가능성이 높음. 따라서 클로즈함.
