### ISSUE TITLE
Infra 1차 확정

### ISSUE THREAD

**Issue by inthewalter** [connect-foundation/2019-12#4]
(예약 서버에 대한 redis 검증 / FE 배포 인프라 확정)

**Comment by FullOfOrange** [comment]
https://github.com/connect-foundation/2019-12/wiki/Infra-Structure
관련 내용을 작성해놓음. 임시적으로 1차 확정임

**Comment by doong-jo** [comment]
처음에 스케치한 구조도 올려주시면 좋을 것 같습니다

**Comment by inthewalter** [comment]
@FullOfOrange

**Comment by FullOfOrange** [comment]
Wiki에 1차적으로 올라간 형태로 배포할 예정입니다.
