### ISSUE TITLE
이미지 타입 추가 및 getImageURL 적용

### ISSUE THREAD

**Issue by dobest27** [connect-foundation/2019-12#428]
### 테스트 환경
bookus

### 오류 내용
- 이벤트 디테일 구매 페이지에서 이미지 나오지 않음
  - 리사이징된 이미지로 불러오고 있지 않음
  - 이미지 타입 추가 및 getImageURL 적용
- 이벤트 디테일 페이지 이미지 크기 조정 필요
  - 썸네일 이미지 사이즈를 사용하고 있음

**Comment by doong-jo** [comment]
merge and close
