### ISSUE TITLE
메인에서 로그인 request 시 useApiRequest 에서 오류가 남

### ISSUE THREAD

**Issue by dobest27** [connect-foundation/2019-12#432]
### 테스트 환경
로컬 및 라이브

### 수행 절차
메인에서 빠르게 반복적으로 새로고침함

### 오류 내용
에러 발생..!

### 참고(스크린샷 등)
<img width="735" alt="스크린샷 2019-12-18 오후 2 37 56" src="https://user-images.githubusercontent.com/6308222/71058698-062a2580-21a4-11ea-9673-29b21609631c.png">

**Comment by doong-jo** [comment]
merge and close
