### ISSUE TITLE
이벤트 상세 페이지에서 주최자 정보를 hover 했을 때 인터랙션 제거

### ISSUE THREAD

**Issue by dobest27** [connect-foundation/2019-12#435]
### Explanation

이벤트 상세 페이지에서 주최자 정보를 hover 했을 때 인터랙션 제거
주최자 페이지가 없어 완성되지 않은 느낌을 주므로 인터랙션 및 아이콘을 제거하는게 어떨지요?

![screencast-localhost_3000-2019 12 18-15_50_45-_1_](https://user-images.githubusercontent.com/6308222/71062637-5ad29e00-21ae-11ea-81da-a7c50d957846.gif)

**Comment by doong-jo** [comment]
resolve and close
