### ISSUE TITLE
이벤트 예약 Alert 문구 수정

### ISSUE THREAD

**Issue by inthewalter** [connect-foundation/2019-12#484]
![Screenshot_20191219-225132_Slack](https://user-images.githubusercontent.com/28642472/71178773-3829ad80-22b2-11ea-83d7-0d0bc5dd6fdb.jpg)

아예 상수에 이/가 를 붙이는 방안으로 해결 생각

---
이/가 가 아니라 아예 각각의 상수로 구현!

**Comment by doong-jo** [comment]
merge and close
