### ISSUE TITLE
각 페이지에 대한 기존 Cypress 테스트 케이스 추가

### ISSUE THREAD

**Issue by doong-jo** [connect-foundation/2019-12#499]
### Explanation

- [ ] 마이페이지
- [ ] 이벤트 상세
- [ ] 이벤트 예약

기능이 완료됨에 따라 추가 테스트를 진행

**Comment by inthewalter** [comment]
성동님 코드보고 배우면서 이벤트만들기도 진행하겠습니다ㅎㅎ

**Comment by doong-jo** [comment]
merge and close
