### ISSUE TITLE
TEST 환경 구성

### ISSUE THREAD

**Issue by inthewalter** [connect-foundation/2019-12#5]
# Backend
- BE, FE 에 대한 디렉토리 / branch 별 테스팅에 대한 config 설정해야함
- DB 테스팅을 위한 Travis - BE 테스트 환경 조성해야함

# Frontend
- Cypress script (React App에 대한 테스트, Storybook에 대한 테스트)

**Comment by doong-jo** [comment]
#53 에서 완료되었음
