### ISSUE TITLE
이미지 셀렉터에서 이미지 선택 후 -> 다시 선택 하고 취소 시 오류

### ISSUE THREAD

**Issue by dobest27** [connect-foundation/2019-12#503]
### 테스트 환경
실서버

### 수행 절차
이벤트 만들기에서 image selector

### 오류 내용
이미지 셀렉터에서 이미지 선택 후 -> 다시 선택 하고 취소 시 오류

### 참고(스크린샷 등)
<img width="438" alt="스크린샷 2019-12-20 오후 3 52 23" src="https://user-images.githubusercontent.com/6308222/71235856-b9c81c80-2340-11ea-9511-faab5bac485a.png">

**Comment by doong-jo** [comment]
merege and close
