### ISSUE TITLE
테스트용 이벤트를 만들어야함. 

### ISSUE THREAD

**Issue by FullOfOrange** [connect-foundation/2019-12#511]
### Explanation

- 이벤트 일정이 종료됨
- 언제든지 구매 가능/환불 가능한 이벤트
- 환불 기간이 지난 이벤트
- 판매 기간이 지난 이벤트
- 판매가 시작되고, 아직 판매기간이 남은 이벤트
- 매진된 이벤트
- 1인당 구매 수량이 모두 찬 이벤트

위와 같은 내용으로 만들어야함.

**Comment by doong-jo** [comment]
merge and close
