### ISSUE TITLE
전역 스타일 및 Theme 설정

### ISSUE THREAD

**Issue by doong-jo** [connect-foundation/2019-12#53]
### Explanation

- Nomalize : CSS 초기화
- GlobalStyles : (*, body ... )에 전역적인 스타일 설정 
- Theme : 사이트에 적용되는 테마 스타일

React App, Storybook에 적용

**Comment by FullOfOrange** [comment]
워커홀릭 성동님

**Comment by inthewalter** [comment]
chk하겠습니다

**Comment by doong-jo** [comment]
#57 에서 PR 진행 중
