### ISSUE TITLE
Base Component 작성

### ISSUE THREAD

**Issue by doong-jo** [connect-foundation/2019-12#59]
Base Component를 작성하고 새로운 Component를 작성할 때 이를 활용하기로 결정함

 - Atom
    - [x] Btn
    - [x] Input
    - [x] Icon
    - [x] Label
    - [x] Divider

- Molecules
    - [x] Card
    - [x] IconBtn

- Organisms
    - [x] Footer
    - [x] Header

**Comment by inthewalter** [comment]
@doong-jo 성동님 feature-59 브런치에서 작업 중입니다.

feature-19 브런치를 theme로 병합하시는 과정 중에 파일들이 다 사라지긴 했는데, 새로운 마음으로 재출발 하고 있습니다!

**Comment by doong-jo** [comment]
> @doong-jo 성동님 feature-59 브런치에서 작업 중입니다.
> 
> feature-19 브런치를 theme로 병합하시는 과정 중에 파일들이 다 사라지긴 했는데, 새로운 마음으로 재출발 하고 있습니다!

ㅜㅜ 넵

**Comment by inthewalter** [comment]
#70 PR 완료
