### ISSUE TITLE
[5/4MD] EventDetailPage (+리팩토링ing)

### ISSUE THREAD

**Issue by inthewalter** [connect-foundation/2019-12#61]
### Page

이벤트 상세 페이지

### Components
![image](https://user-images.githubusercontent.com/28642472/69019214-ee1f8480-09f2-11ea-9d49-2ba373699f92.png)
- [x] EventBannerContainer
  - [x] BannerImg
  - [x] DescContainer
    - [x] Title
    - [x] Location
    - [x] Date
    - [x] HostContainer
      - [x] Img
      - [x] Name

![image](https://user-images.githubusercontent.com/28642472/69019226-f8418300-09f2-11ea-9e53-fbd3435067c2.png)
- [x] TicketBuyContainer
  - [x] Title
  - [x] Price
  - [x] ParticipantCnt
  - [x] BuyBtn

![image](https://user-images.githubusercontent.com/28642472/69019243-1313f780-09f3-11ea-9289-d07cb159887a.png)
- [x] EventDesc

![image](https://user-images.githubusercontent.com/28642472/69019287-53737580-09f3-11ea-8231-5fff262fef42.png)
- [x] TicketList
  - [x] TicketListLabel
  - [x] TicketContainer
    - [x] Price
    - [x] Name
    - [x] Desc
    - [x] LeftCnt
    - [x] LimitCntPerPerson
    - [x] EndDate
    - [x] ParticipantCnt

![image](https://user-images.githubusercontent.com/28642472/69019305-5c644700-09f3-11ea-9f23-34bd9a0f0619.png)
- [x] LocationContainer
  - [x] Label
  - [x] Place
  - [x] Address
  - [x] Desc

- Refactoring
  - [x] template / organisms 분리

**Comment by doong-jo** [comment]
merge and close
