### ISSUE TITLE
네이버 지도 API

### ISSUE THREAD

**Issue by FullOfOrange** [connect-foundation/2019-12#62]
### Component

NaverMapContainer (네이버 지도 API)

### Screenshot

<img width="1056" alt="스크린샷 2019-11-18 오전 11 01 00" src="https://user-images.githubusercontent.com/10372359/69019364-ab11e100-09f3-11ea-8798-6d1f5480c82c.png">

### Page

#61 

### Explanation

주소를 통해서 네이버 지도에 위치를 보여줌

**Comment by doong-jo** [comment]
네이버 지도는 사용하지 않으므로 close
