### ISSUE TITLE
클라이언트 Precommit 버그 🔥

### ISSUE THREAD

**Issue by inthewalter** [connect-foundation/2019-12#95]
### 테스트 환경
새롭게 클론받아서 커밋을 수행함

### 수행 절차
1. 새롭게 클론 
2. `yarn workspace client lint` 통과!
3. commit 실패!
4. `yarn workspace client precommit` 실패!!

### 오류 내용

머지하는 과정에서 클라이언트의 package.json 파일의 lint-staged 과정이 변경된 것 같음
```json
  "lint-staged": {
    "*.{ts,tsx,js,jsx,json,scss,css,md}": [
      "prettier --write",
      "git add"
    ],
    "*.{ts,tsx}": [
      "tsc --noEmit --strict --skipLibCheck --esModuleInterop --jsx react",
      "git add"
    ],
    "*.{ts,tsx,js,jsx}": [
      "eslint --fix",
      "git add"
    ]
  }
```

### 기대 결과
```json
  "lint-staged": {
    "*.{ts,tsx,js,jsx}": [
      "eslint --fix",
      "git add"
    ]
  }
```
이렇게 되면 되지 않을까요 ㅇ-ㅇ?

### 참고(스크린샷 등)
![image](https://user-images.githubusercontent.com/28642472/69503748-75737780-0f60-11ea-9059-971846220ce1.png)

**Comment by dobest27** [comment]
https://stackoverflow.com/questions/44717164/unable-to-import-svg-files-in-typescript

**Comment by dobest27** [comment]
해결 했습니다 👍
