### ISSUE TITLE
날짜 관련 유틸이 필요

### ISSUE THREAD

**Issue by inthewalter** [connect-foundation/2019-12#96]
### Explanation

![image](https://user-images.githubusercontent.com/28642472/69504362-6f33ca00-0f65-11ea-847a-8794246be1ee.png)
![image](https://user-images.githubusercontent.com/28642472/69504372-75c24180-0f65-11ea-9a0d-b52279857b57.png)
![image](https://user-images.githubusercontent.com/28642472/69504383-85da2100-0f65-11ea-92e6-f60c8d4937b8.png)

DB에는 데이터가 `2018-02-24T01:30:00.000Z`식으로 저장되지만
위와 같이 다양한 날짜들이 나오기 때문에 유틸이 필요해 보임,,,

**Comment by FullOfOrange** [comment]
에어비엔비 캘린더 보면 moment 라는 모듈 쓰더라고요

**Comment by dobest27** [comment]
moment 말고 다른 대체재가 있나요~?

**Comment by dobest27** [comment]
음 꼭 필요한가요?

**Comment by doong-jo** [comment]
기본 HTML로 구현하면 좋겠지만 쓴다면 moment

**Comment by dobest27** [comment]
moment 사용
이슈 닫아용
