### ISSUE TITLE
[1*3MD] State 관리 방법 정해야함

### ISSUE THREAD

**Issue by FullOfOrange** [connect-foundation/2019-12#97]
### Explanation

각각의 컴포넌트와 State에 대한 관리 방법을 지정해야함. 

Components, Page를 아우르는 State 관리 방법이 필요함. hooks를 사용하기로 결정됨.

**Comment by FullOfOrange** [comment]
#99 로써 해결됨 PR이 닫히면 클로즈를 할 예정

**Comment by dobest27** [comment]
완료~!
